### ISSUE TITLE
IRouter interface wrond methods signatures

### ISSUE THREAD

**Issue by mosinnik** [dystopia-exchange/dystopia-contracts#45]
at least getAmountOut method signatures are different in interface:
https://github.com/dystopia-exchange/dystopia-contracts/blob/efd5780ad1d7022fdee30f14868b2eb1fd960886/contracts/interface/IRouter.sol#L115
and in router:
https://github.com/dystopia-exchange/dystopia-contracts/blob/efd5780ad1d7022fdee30f14868b2eb1fd960886/contracts/base/periphery/DystRouter01.sol#L90

other methods are not exists in router at all and some (like swapExactTokensForTokensSimple) lost in interface

**Comment by belbix** [comment]
fixed in #50
